# Build stage
FROM node:16 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Inject environment variables into the build process
ARG VUE_APP_API_TOKEN
ARG VUE_APP_SERVER_URL
ARG VUE_APP_GITHUB_CLIENT_ID
ARG VUE_APP_GITHUB_CLIENT_SECRET
ARG VUE_APP_GITHUB_CALLBACK_URL
ENV VUE_APP_API_TOKEN=$VUE_APP_API_TOKEN
ENV VUE_APP_SERVER_URL=$VUE_APP_SERVER_URL
ENV VUE_APP_GITHUB_CLIENT_ID=$VUE_APP_GITHUB_CLIENT_ID
ENV VUE_APP_GITHUB_CLIENT_SECRET=$VUE_APP_GITHUB_CLIENT_SECRET
ENV VUE_APP_GITHUB_CALLBACK_URL=$VUE_APP_GITHUB_CALLBACK_URL

RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 92
CMD ["nginx", "-g", "daemon off;"]